[package]
name = "web_v0"
version = "0.1.0"
edition = "2021"

[dependencies]
# tui = "0.19"
# crossterm = "0.26"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
crossterm = "0.25"
tui = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

